
modLoader="javafml" #mandatory

loaderVersion="[36,)" 

license="All rights reserved"

issueTrackerURL="https://github.com/Nater0097/Trinity/issues"

[[mods]] #mandatory

modId="trinity" #mandatory

version="1.6.0" #mandatory

displayName="TrinityWeapons" #mandatory

updateJSONURL="https://raw.githubusercontent.com/Nater0097/StuffThatINeed/master/UpdateChecker.json"

displayURL="https://www.curseforge.com/minecraft/mc-mods/trinityweapons" #optional

logoFile="logo.png"

credits="Devilb666(Artist)" #optional

authors="Nathan(Thermionic)" #optional

description='''

TrinityWeapons adds new and exciting weapons into Minecraft! From the Cavemen to Covid-19, we have all the weapons..

'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.trinity]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5)"
    ordering="NONE"
    side="BOTH"
