modLoader="javafml" #mandatory

loaderVersion="[28,)" 

license="All Rights Reserved"

issueTrackerURL="https://github.com/Nater0097/Trinity/issues"

logoFile="logo.png"

[[mods]] #mandatory

modId="trinity" #mandatory

version="1.5.0" #mandatory

displayName="TrinityWeapons" #mandatory

updateJSONURL="https://raw.githubusercontent.com/Nater0097/StuffThatINeed/master/UpdateChecker.json"

displayURL="https://www.curseforge.com/minecraft/mc-mods/trinityweapons" #optional

credits="Devilb666(Artist) \n You, For downloading this incredible mod!" #optional

authors="Nathan(Thermionic)" #optional

description='''

TrinityWeapons adds new and exciting weapons into Minecraft! From the Cavemen to Covid-19, we have all the weapons..

'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.trinity]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"